# TODO Workflow of TASK THREE GOES HERE
name: Authenticate User

on:
  workflow_dispatch:

jobs:
  authenticate:
    runs-on: ubuntu-latest
    if: ${{ github.actor }} == 'NayakSubhangi'
    steps:
      - name: Find Github Actor
        run: |
          echo "${{ github.actor }} triggered this workflow"
  
  job2:
    runs-on: ubuntu-latest
    needs: authenticate
    steps:
      - name: Print Message
        run: |
          echo "This is job2"

  job3:
    runs-on: ubuntu-latest
    needs: authenticate
    steps:
      - name: Print Message
        run: |
          echo "This is job3"