name: Demo 6 Workflow

on:
  workflow_dispatch:
    inputs:
      string1:
        description: "Enter String One (github_env or github_output)"
      boolean1:
        description: "Enter Boolean One (True or False)"
        type: boolean

jobs:
  job1:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.string1 != '' }}
    outputs:
      MY_OUTPUT: ${{ steps.output123.outputs.MY_OUTPUT }}
    steps:
      - name: Set Environment If Github Environment
        if: ${{ github.event.inputs.string1 == 'github_env' }}
        run: |
          echo "MY_ENV=hello_from_environment" >> $GITHUB_ENV
          echo "Environment Variable Set Successfully"

      - name: Display Environment
        if: ${{ github.event.inputs.string1 == 'github_env' }}
        run: |
          echo "my_env is ${{ env.MY_ENV }}"
      
      - name: Set Output If Github Output
        id: output123
        if: ${{ github.event.inputs.string1 == 'github_output' }}
        run: |
          echo "MY_OUTPUT=hello_from_output" >> $GITHUB_OUTPUT
          echo "Output Variable Set Successfully"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: ${{ github.event.inputs.string1 == 'github_output' }}
    steps:
      - name: Display Output
        run: |
          echo "my_output is ${needs.job1.outputs.MY_OUTPUT }}"
  
  job3:
    runs-on: ubuntu-latest
    needs: job2
    # if: ${{ always() }} # When using always(), job3 will run regardless of whether job2 succeeds or fails, or even if the workflow is cancelled.
    if: ${{ success() || failure() }} # When using success(), job3 will run if job2 succeeds,
    # and when using failure(), job3 will run if job2 fails.
    # So, job3 will run regardless of whether job2 succeeds or fails,
    # but will stop if the workflow is cancelled.
    steps:
      - name: Display Message If True
        if: ${{ github.event.inputs.boolean1 == 'true' }}
        run: |
          echo "This is from job3"
          echo "boolean1 is true"
      
      - name: Display Message If False
        if: ${{ github.event.inputs.boolean1 == 'false' }}
        run: |
          echo "This is from job3"
          echo "boolean1 is false"
