name: Display Secrets and Variables

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Display Github Secrets
        run: |
          echo "Here's a secret!"
          echo "${{ secrets.GIT_ACCOUNT }}"
  
  job2:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Display Github Variables
        run: |
          echo "Here's a variable: ${{ vars.GIT_PASSWORD }}"
