name: Using Matrix with Multiple Values in os

on:
    workflow_dispatch:

jobs:
    job1:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        steps:
          - name: Display
            run: |
             echo "Hello!"

# TASK TWO: (DONE)
# Clean up the vscode workspace and move the PythonProgramming (which should be renamed)

# TASK FOUR: (DONE)
# Brush up on Reusable workflows, and Cron Job.